changelog:
  categories:
    - title: "Features"
      labels:
        - "feature"
    - title: "Fixes"
      labels:
        - "bug"
    - title: "Docs & Chores"
      labels:
        - "docs"
        - "chore"
  exclude:
    labels:
      - "ignore-for-release"
